name: install
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/install.yml"
      - "install.sh"
  pull_request:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare
        timeout-minutes: 360
        run: |
          cd ~
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install curl git -y
          source /etc/os-release
          curl --retry 100 --retry-connrefused --retry-delay 5 -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc >/dev/null
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $UBUNTU_CODENAME stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install docker-ce -y
          git clone https://github.com/Willie169/termux-android-sdk-ndk.git
          cd termux-android-sdk-ndk
          sed -Ei 's|(#!/data/data/com\.termux/files/usr/bin/bash)|\1\nset -euxo pipefail|; s|pkg |apt |' install.sh
      - name: Run install.sh
        timeout-minutes: 360
        run: |
          docker run --rm -v "$HOME/termux-android-sdk-ndk:/data/data/com.termux/files/home/termux-android-sdk-ndk" -w "/data/data/com.termux/files/home/termux-android-sdk-ndk" --privileged termux/termux-docker bash -c '
            set -euxo pipefail
            echo "deb https://packages.termux.dev/apt/termux-main stable main" > /data/data/com.termux/files/usr/etc/apt/sources.list
            ./install.sh "platform-tools"
          '
